const PROJECTS = {
    makeyourgame: {
        name: 'Make Your Game',
        repo: 'https://github.com/nater6/make-your-game-score-handling',
        images: ['', '', ''],
        description: `The objective of this project was to remake the classic donkey kong game. The game runs at 60 FPS and uses RequestAnimationFrame. When the player finishes they can 
        input their results into the leaderboard and see hwo their results compare. The game doesn't use canvas or any frameworks, so I could get used to manipulating DOM with vanilla JavaScript.`,
        skills: ['DOM', 'Event Loop', 'Dev Tools'],
        features: [
            '60 FPS',
            'No Frame Drops',
            'Leaderboard',
            'Pause Menu',
            'Continue and Restart Options',
            'Scoreboard (Time, Score & Lives)',
        ],
    },
    lemin: {
        name: 'Lemin',
        repo: 'https://github.com/nater6/lem-in',
        images: ['', '', ''],
        description: ``,
        skills: ['', ''],
        features: ['', ''],
    },
    misterquiz: {
        name: 'Mister Quiz',
        repo: 'https://github.com/nater6/mister-quiz',
        images: ['', '', ''],
        description: ``,
        skills: ['', ''],
        features: ['', ''],
    },
    forum: {
        name: 'Forum',
        repo: 'https://github.com/codecplyre/real-time-forum/-',
        images: ['', '', ''],
        description: `This project was to make a forum for coders. It was aimed at 01Founder students. Users can make posts, comment and message other users. As well as that, users can filter through
        posts, by category, and select favourites. Messages are sent in real time. Users are notified when the chat recipient is
        typing and when they recieve a message.`,
        skills: [
            'Websockets',
            'UI',
            'DOM',
            'Go Routines',
            'Go Channels',
            'APIs',
            'HTTP',
            'Sessions',
            'Cookies',
            'encryption',
            'SQL Database',
        ],
        features: [
            'Creating Posts',
            'Commenting',
            'Live Messaging',
            'Filtering',
            'User is Typing Notification',
            'New Post Notification',
            'Message Notification',
        ],
    },
    groupietracker: {
        name: 'Groupie Tracker',
        repo: 'https://github.com/nater6/groupie-tracker-visualisations',
        images: ['', '', ''],
        description: ``,
        skills: ['', ''],
        features: ['', ''],
    },
    asciiartweb: {
        name: 'Ascii Art Web',
        repo: 'https://github.com/nater6/ascii-art-web',
        images: ['', '', ''],
        description: ``,
        skills: ['', ''],
        features: ['', ''],
    },
};
